const mockVehicles = [
  {
    make: 'Ford',
    model: 'Mustang',
    year: 2023,
    price: 35000,
    bodyStyle: 'Coupe',
    engine: '3.0L V6',
    transmission: 'Automatic',
    drivetrain: 'Rear-Wheel Drive',
    exterior: 'Red',
    kilometers: 50000,
    doors: 2,
    stock: '12345',
    vin: '1HGCM82633A123456',
    fuelType: 'Gasoline',
    condition: 'Excellent',
    images: 'https://example.com/ford-mustang.jpg',
    description: 'The Ford Mustang is a legendary American muscle car known for its powerful performance and iconic design.'
  },
  {
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2023,
    price: 37000,
    bodyStyle: 'Coupe',
    engine: '2.0L Turbocharged Inline-4',
    transmission: 'Automatic',
    drivetrain: 'Rear-Wheel Drive',
    exterior: 'Black',
    kilometers: 20000,
    doors: 2,
    stock: '67890',
    vin: '1C6RR7MT4ES123456',
    fuelType: 'Gasoline',
    condition: 'Good',
    images: 'https://example.com/chevrolet-camaro.jpg',
    description: 'The Chevrolet Camaro is a sleek and sporty coupe that offers a thrilling driving experience and eye-catching style.'
  },
  {
    make: 'Dodge',
    model: 'Charger',
    year: 2023,
    price: 40000,
    bodyStyle: 'Sedan',
    engine: '3.6L V6',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    exterior: 'White',
    kilometers: 30000,
    doors: 4,
    stock: '23456',
    vin: '2G1FD1ED5E92654321',
    fuelType: 'Gasoline',
    condition: 'Very Good',
    images: 'https://example.com/dodge-charger.jpg',
    description: 'The Dodge Charger is a powerful and spacious sedan with aggressive styling and a comfortable interior.'
  },
  {
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 80000,
    bodyStyle: 'Sedan',
    engine: 'Electric',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    exterior: 'Blue',
    kilometers: 10000,
    doors: 4,
    stock: '78901',
    vin: '5YJSA1E45FF123456',
    fuelType: 'Electric',
    condition: 'Like New',
    images: 'https://example.com/tesla-model-s.jpg',
    description: 'The Tesla Model S is a luxury electric sedan known for its impressive range, cutting-edge technology, and smooth acceleration.'
  },
  {
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 25000,
    bodyStyle: 'Sedan',
    engine: '2.0L Inline-4',
    transmission: 'Automatic',
    drivetrain: 'Front-Wheel Drive',
    exterior: 'Silver',
    kilometers: 40000,
    doors: 4,
    stock: '34567',
    vin: 'JHMFA3F26DS123456',
    fuelType: 'Gasoline',
    condition: 'Good',
    images: [
      'https://blogmedia.dealerfire.com/wp-content/uploads/sites/818/2018/06/2018-Honda-Civic-Sedan-in-Lunar-SIlver-Metallic_o.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvpj64pG1bOvLsh3tfCC_n2Urj7q7aHPr-W7lrIk51&s',
      'https://images.cars.com/cldstatic/wp-content/uploads/honda-civic-hatchback-2021-OEM-exterior--silver.jpg'
    ],
    description: 'The Honda Civic is a reliable and fuel-efficient sedan that offers a comfortable ride and modern features.'
  },
];

export default mockVehicles;
