const mockVehicles = [
  // Existing vehicles (Toyota Camry and Ford F-150)
  {
    title: "Toyota Camry",
    cost: 25000,
    kilometers: 15000,
    engine: "2.5L 4-cylinder",
    drivetrain: "Front-Wheel Drive",
    exterior: "Silver",
    doors: 4,
    stockNumber: "123456",
    vin: "1HGCM82633A001234",
    condition: "Used",
    transmission: "Automatic",
    description: "A reliable and fuel-efficient sedan.",
    images: [
      "https://example.com/toyota_camry_front.jpg",
      "https://example.com/toyota_camry_back.jpg",
      "https://example.com/toyota_camry_interior.jpg",
    ],
  },
  {
    title: "Ford F-150",
    cost: 35000,
    kilometers: 8000,
    engine: "3.5L V6",
    drivetrain: "4x4",
    exterior: "Blue",
    doors: 2,
    stockNumber: "987654",
    vin: "1FTFX1E83AFA87654",
    condition: "New",
    transmission: "Automatic",
    description: "A rugged and powerful pickup truck.",
    images: [
      "https://example.com/ford_f150_front.jpg",
      "https://example.com/ford_f150_back.jpg",
      "https://example.com/ford_f150_interior.jpg",
    ],
  },
  // New vehicles
  {
    title: "2023 Chevrolet Corvette Stingray",
    cost: 70000,
    kilometers: 100,
    engine: "6.2L V8",
    drivetrain: "Rear-Wheel Drive",
    exterior: "Red",
    doors: 2,
    stockNumber: "777777",
    vin: "1G1Y72D40L5111111",
    condition: "New",
    transmission: "Automatic",
    description: "A high-performance sports car.",
    images: [
      "https://example.com/chevrolet_corvette_front.jpg",
      "https://example.com/chevrolet_corvette_back.jpg",
      "https://example.com/chevrolet_corvette_interior.jpg",
    ],
  },
  {
    title: "2023 Ford Mustang GT Premium",
    cost: 60000,
    kilometers: 500,
    engine: "5.0L V8",
    drivetrain: "Rear-Wheel Drive",
    exterior: "Yellow",
    doors: 2,
    stockNumber: "888888",
    vin: "1FA6P8CF9L5500000",
    condition: "New",
    transmission: "Automatic",
    description: "An iconic American muscle car.",
    images: [
      "https://example.com/ford_mustang_gt_front.jpg",
      "https://example.com/ford_mustang_gt_back.jpg",
      "https://example.com/ford_mustang_gt_interior.jpg",
    ],
  },
  {
    title: "2023 Honda Civic Sedan LX-B CVT",
    cost: 28000,
    kilometers: 200,
    engine: "1.8L 4-cylinder",
    drivetrain: "Front-Wheel Drive",
    exterior: "Silver",
    doors: 4,
    stockNumber: "999999",
    vin: "2HGFC2F7XPH555555",
    condition: "New",
    transmission: "CVT",
    description: "The Honda Civic is a reliable and fuel-efficient sedan that offers a comfortable ride and modern features. It's a great choice for a daily driver. From its standard 2.0-liter 4-cylinder engine to the more powerful 1.5-liter turbocharged option, the Civic strikes a great balance between performance and fuel economy.",
    images: [
      "https://blogmedia.dealerfire.com/wp-content/uploads/sites/818/2018/06/2018-Honda-Civic-Sedan-in-Lunar-SIlver-Metallic_o.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvpj64pG1bOvLsh3tfCC_n2Urj7q7aHPr-W7lrIk51&s",
      "https://images.cars.com/cldstatic/wp-content/uploads/honda-civic-hatchback-2021-OEM-exterior--silver.jpg",
    ],
  },
];


export default mockVehicles;
